### PR TITLE
Modify GUI - allow showing multi-line values

### PR DESCRIPTION
**Pull request by GitHubDragonFly**

### CODE REVIEW

**Comment by GitHubDragonFly** [comment]
Another Note on 1.0.0.b1:
- SLCDriver string reading shows all 82 bytes, like this:
  - address ST9:0{2} shows the actual strings, which might be 5 char long, plus all "\x00" as if spaces
  - addresses ST9:0{2} ; N7:0{3} as a multi-tag, show the actual strings, which might be 5 char long, plus all literal "\x00" chars

**Comment by ottowayi** [comment]
interesting on the SLCDriver and strings, I was having issues trying to use the SLC mapping inside Logix to test it.  But, it probably wasn't working to begin with if you had to add the `'{2}'`.  I have a MicroLogix that I need to get wired up, but I'll be able to use that to test the SLCDriver

**Comment by GitHubDragonFly** [comment]
The {2} was there only because it's a maximum strings one could read.

Here is the picture of 2 different tag readings.

MLGX String Reading

**Comment by ottowayi** [comment]
Ohh I understand.  Yeah it's returning the entire string, not truncating based on the LEN.  That's a bug that should get fixed, for now you can just call `strip()` on the value and it should take care of it.

**Comment by GitHubDragonFly** [comment]
I did fix this string reading using strip() but your current library still seems to have an issue with bool arrays addressing, where these results are shown:

CT_BOOLArray[x] = False or True
CT_BOOLArray[0]{1} = error "bool object is not iterable"  (I would expect to see either False or True)
CT_BOOLArray[x]{2} = 64 bool values  (I would expect to see 2 consecutive bool values starting at "x")
CT_BOOLArray[x]{3} = 96 bool values  (I would expect to see 3 consecutive bool values starting at "x")

**Comment by ottowayi** [comment]
Bool arrays are a pain in the ass and require special handling due to how the are implemented in the PLC.  The reason you can only make arrays with multiple of 32 is because they are stored as a DWORD array.   `{2}` means get two elements from this array, which translates to 2 DWORD elements, or 64 BOOLs.  The `{1}` only returning one boolean is a bug, the others are 'correct' - but, yeah I get that they wouldn't be what you are expecting.   I did plan on changing the meaning of '{#}' for BOOLs so that it refers to the BOOL elements and not underlying DWORD elements, but I hit a roadblock and decided to hold off.  I don't remember what that issue was, but I will look into again and see if what I can do about it.  I agree that it currently is confusing.

**Comment by GitHubDragonFly** [comment]
I was just pointing it out, so take your time.

If it's of any help to you, pylogix seems to be handling bool arrays properly (maybe check the way they did it).

**Comment by GitHubDragonFly** [comment]
Your latest changes appear to have made BOOL arrays working properly.

The driver was choking with open() function, producing an error: "failed isolating user tags".
This appears to be related to the presence of any ALARMS tag (try creating a tag of ALARM_ANALOG type for a test).

**Comment by ottowayi** [comment]
Yeah the latest changes changed the meaning of the element count to mean number of BOOL elements, not underlying DWORD array elements.  They 'worked properly' before, but the semantics were based on them being DWORD arrays internally, while users typically only see them as BOOL arrays.  

Part of the changes did fix some errors on handling builtin types, but I didn't test them against ANALOG_ALARM tags.  Those appear to not be as simple as the other types and there was a bug that made some assumptions about them.  I pushed a fix that resolves the parsing issue, but you will not be able to read/write them as a complete struct.  The PLC returns a 'permission denied' error, I'm guessing because these are alarms they need to be more 'secure'.  You will need to read individual attributes instead.

**Comment by GitHubDragonFly** [comment]
It all appears to be working fine with your develop branch.

I did update the lgx_gui_test.py in the examples and created a PR.
It's kind of all optional so you decide whether to merge it.

**Comment by GitHubDragonFly** [comment]
Just to point this out, somewhat similar to BOOL arrays, your driver doesn't seem to allow listing multiple bits of a single tag, for example: CT_DINT.0{6}

It does allow reading individual bits: CT_DINT.0; CT_DINT.1; CT_DINT.2; CT_DINT.3; CT_DINT.4; CT_DINT.5

It would be an improvement if you could implement that as well.

**Comment by ottowayi** [comment]
Yeah that currently is not supported. If you believe it's an important feature, please open up an issue for it.

**Pull request merged**
